### ISSUE TITLE
navplayer command returns error in 1.18.1

### ISSUE THREAD

**Issue by ralfdonald** [ThomasVerschoor/BetterNav#9]
Using BetterNav in 1.18.1 returns an the error "Cannot cast navigation to yourself" if trying to navigate to another player.

**Comment by ThomasVerschoor** [comment]
Thanks for noticing! I'm kinda busy on my exams right now, but I'll take a look at it and fix the issue when I'm done!

**Comment by ThomasVerschoor** [comment]
Hi @ralfdonald! I'm going to close this issue, the new update should fix the error! Thanks for noticing, keep navigating!
